version: "3"

services:
  common-tools:
    image: 'nginx:alpine'
    container_name: common-tools
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - 8080:80
networks:
  nginx-proxy-manager:
    external: true
