version: "3"

services:
   common-tools:
     container_name: common-tools
     image: app
     build:
       context: .
       dockerfile: Dockerfile
     restart: unless-stopped
     ports:
       - 8080:8080
networks:
  nginx-proxy-manager:
    external: true
